GET http://nixtst01:15000/rest/authenticate
Authorization: basic YWRtaW46YWRtaW4=
###
GET http://localhost:8080/rest/authenticate
Authorization: basic YWRtaW46YWRtaW4=

### hvad er contented //nixt01:35000 er QA
GET http://localhost:8080/rest/list/1/items/YEL/0/10/InvoiceId/385987
Authorization: Next 9S2NGN2ZENS6WEKDENP78TB1E9HPGTBPCMX7AWV5E8X42H2D9570_M5P97AVD9W5JJV9WDXDS19R

### fulltext / vælg preview, hvis mulig
GET http://nixtst01:15000/rest/id/1/urn:multiarchive:content:YEL:36965-36968?representation=fulltext
Authorization: Next 9S2NGN2ZENS6WEKDENP78TB1E9HPGTBPCMX7AWV5E8X42H2D9570_YMKV642K8C86Q4V3ZD40

### Original
GET http://nixtst01:15000/rest/id/1/urn:multiarchive:content:YEL:36965-36968
Authorization: Next 9S2NGN2ZENS6WEKDENP78TB1E9HPGTBPCMX7AWV5E8X42H2D9570_YMKV642K8C86Q4V3ZD40

### Uffe
http://localhost:8080/rest/id/1/urn:multiarchive:content:TST:520-523%231-1?cred=9S2NGN2ZENS6WEKDENP78TB1E9HPGTBPCMX7AWV5E8X42H2D9570_654PBPEYHAZC1ZYR&representation=preview

###
http://localhost:8080/rest/content/1/urn:multiarchive:content:YEL:36965-36968#1-1?cred9S2NGN2ZENS6WEKDENP78TB1E9HPGTBPCMX7AWV5E8X42H2D9570_654PBPEYHAZC1ZYR